# Generated by Django 2.0.7 on 2018-07-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_auto_20180714_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='user',
            new_name='user_id',
        ),
    ]
